stages:
    - test
    - build
    - push

variables:
    project: "agent"

ci-test:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: test
    script:
        - cargo check -j 2 -v

agent-build-x86:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: build
    script:
        - export AD_VERSION="${CI_COMMIT_TAG:=$CI_PIPELINE_ID.0.0}"
        - sed -i "0,/0.1.0/ s/0.1.0/${AD_VERSION}/" core_lib/Cargo.toml
        - sed -i "0,/0.1.0/ s/0.1.0/${AD_VERSION}/" daemon/Cargo.toml
        - cargo build -j 2 --release
        - ./build.sh --arch x86_64-unknown-linux-musl --version ${AD_VERSION}
        - mkdir -p build/x86_64 && cp /tmp/ad-agent*.tar.gz build/x86_64/
    only:
        - tags
        - master
    artifacts:
        paths:
            - build
        expire_in: 2 days

agent-build-arm64:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:aarch64-musl
    stage: build
    script:
        - export AD_VERSION="${CI_COMMIT_TAG:=$CI_PIPELINE_ID.0.0}"
        - sed -i "0,/0.1.0/ s/0.1.0/${AD_VERSION}/" core_lib/Cargo.toml
        - sed -i "0,/0.1.0/ s/0.1.0/${AD_VERSION}/" daemon/Cargo.toml
        - cargo build -j 2 --release
        - ./build.sh --arch aarch64-unknown-linux-musl --version ${AD_VERSION}
        - mkdir -p build/arm64 && cp /tmp/ad-agent*.tar.gz build/arm64/
    only:
        - tags
        - master
    artifacts:
        paths:
            - build
        expire_in: 2 days

deploy:
    image: curlimages/curl:7.81.0 
    stage: push
    only:
        - tags
        - master
    script:
        - ./push.sh
