stages:
    - build

variables:
    project: "agent"
    DOCKER_TLS_CERTDIR: ""

agent-build-x86:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: build
    script:
        - cargo build --release
        - ./build.sh --arch x86_64-unknown-linux-musl --version ${CI_COMMIT_TAG}
        - mkdir build && cp /tmp/ad-agent*.tar.gz build/
    artifacts:
        paths:
            - build
        expire_in: 2 days
