stages:
    - test
    - build
    - push

variables:
    project: "agent"

ci-test:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: test
    script:
        - cargo check -v

agent-build-x86:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: build
    script:
        - cargo build --release
        - ./build.sh --arch x86_64-unknown-linux-musl --version ${CI_COMMIT_TAG}
        - mkdir build && cp /tmp/ad-agent*.tar.gz build/
    only:
        - tags
        - master
    artifacts:
        paths:
            - build
        expire_in: 2 days

agent-build-arm64:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:aarch64-musl
    stage: build
    script:
        - cargo build --release
        - ./build.sh --arch aarch64-unknown-linux-musl --version ${CI_COMMIT_TAG}
        - mkdir build && cp /tmp/ad-agent*.tar.gz build/
    only:
        - tags
        - master
    artifacts:
        path:
            - build
        expire_in: 2 days
