stages:
    - build

variables:
    project: "agent"
    DOCKER_TLS_CERTDIR: ""

agent-build-x86:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: build
    script:
        - ls
        - cargo build --release
        - ls
