stages:
    - build

variables:
    project: "agent"
    DOCKER_TLS_CERTDIR: ""

agent-build-x86:
    tags:
        - oraclecloud
    image: messense/rust-musl-cross:x86_64-musl
    stage: build
    script:
        - apt-get update
        - apt-get install -y tree
        - ls
        - cargo build --release
        - ls
        - tree target
    artifacts:
        paths:
            - target/x86_64-unknown-linux-musl/release/ad-agent
        expire_in: 2 days
