[main]
url = "http://google.com:8000/agent-api/v1" # Automatdeck entrypoint url
check_interval = 300    # Check interval in seconds (default: 300)
email = "kheshavsewnundun@gmail.com" # Email of the account
access_key = "f9f4cdb010d449f481647c8e0ce0db58"
secret_key = "8e60da5dea15489b9d4412f5906c93c7"
log_dir = "log" # default: in folder named "log" where ad-agent is installed
log_level = "DEBUG"  # Allowed values: INFO, WARN, DEBUG (default: DEBUG)

[security]
enable_encryption = false # Encrypt data before sending to api (default: false)
key_path = ""

[modules]
module_dir = ""
enabled_modules = [] # Double quoted String separated by comma
